//////////////////////////////////////////////////////////
// Resources file, created with 17buddies php script!!! //
// © Chapo 2005-2007 - Infos @ http://www.17buddies.net //
//          More than 15000 maps to download!           //
//                                                      //
//      Can you play all of our maps ?? Sure not!!      //
//////////////////////////////////////////////////////////
//
// Res file generated by mikado for 17Buddies.
//
// Map Name  : cs_175bikini
//
// Download @: http://dwl.17buddies.net/link/map/6085/cs_175bikini.html
//
//////////////////////////////////////////////////////////
gfx/env/morningdewup.tga
gfx/env/morningdewdn.tga
gfx/env/morningdewlf.tga
gfx/env/morningdewrt.tga
gfx/env/morningdewft.tga
gfx/env/morningdewbk.tga

models/hostage.mdl
models/scientist.mdl
models/uplant1.mdl
models/uplant3.mdl
models/lv_bottle.mdl

sound/ambience/birds9.wav
sound/ambience/birds5.wav
sound/ambience/waterfall3.wav
sound/ambience/industrial4.wav
sound/ambience/biotone.wav
sound/ambience/computalk2.wav
sound/ambience/deadsignal2.wav
sound/ambience/wren1.wav
sound/ambience/birds8.wav
sound/ambience/tankidle1.wav
sound/buttons/latchlocked1.wav
sound/zombie/claw_miss1.wav
sound/hostage/hos1.wav
sound/hostage/hos2.wav
sound/hostage/hos3.wav
sound/hostage/hos4.wav
sound/hostage/hos5.wav

sprites/glow01.spr
sprites/moths.spr
sprites/xsmoke3.spr
sprites/wsplash3.spr