//////////////////////////////////////////////////////////
// Resources file, created with 17buddies php script!!! //
// © Chapo 2005-2007 - Infos @ http://www.17buddies.net //
//          More than 15000 maps to download!           //
//                                                      //
//      Can you play all of our maps ?? Sure not!!      //
//////////////////////////////////////////////////////////
//
// Res file generated by mikado for 17Buddies.
//
// Map Name  : cs_assault2
//
// Download @: http://dwl.17buddies.net/link/map/7572/cs_assault2.html
//
//////////////////////////////////////////////////////////
gfx/env/dawnup.tga
gfx/env/dawndn.tga
gfx/env/dawnlf.tga
gfx/env/dawnrt.tga
gfx/env/dawnft.tga
gfx/env/dawnbk.tga

models/hostage.mdl
