//////////////////////////////////////////////////////////
// Resources file, created with 17buddies php script!!! //
// © Chapo 2005-2007 - Infos @ http://www.17buddies.net //
//          More than 15000 maps to download!           //
//                                                      //
//      Can you play all of our maps ?? Sure not!!      //
//////////////////////////////////////////////////////////
//
// Res file generated by mikado for 17Buddies.
//
// Map Name  : cs_sokak
//
// Download @: http://dwl.17buddies.net/link/map/2186/cs_sokak.html
//
//////////////////////////////////////////////////////////
 
gfx/env/tornskyup.tga
gfx/env/tornskydn.tga
gfx/env/tornskylf.tga
gfx/env/tornskyrt.tga
gfx/env/tornskyft.tga
gfx/env/tornskybk.tga

models/hostage.mdl

sound/ambience/cs_sokakradio.wav
sound/de_torn/torn_ambience.wav
sound/de_torn/torn_water2.wav
