/maps/de_aisle.res
/maps/de_aisle.bsp
/maps/de_aisle.txt
/gfx/env/sky_day01_06dn.tga
/gfx/env/sky_day01_06up.tga
/gfx/env/sky_day01_06ft.tga
/gfx/env/sky_day01_06rt.tga
/gfx/env/sky_day01_06lf.tga
/gfx/env/sky_day01_06bk.tga
/models/de_aisle/car_lada.mdl
/models/de_aisle/rustcar3.mdl
/models/de_aisle/bicycle.mdl
/models/de_aisle/bush_noleaves.mdl
/models/de_aisle/bush_fern_small.mdl
/models/de_aisle/tree_noleves.mdl
/models/de_aisle/slltreet.mdl
/sond/de_aisle/keycat1.wav
/overviews/de_aisle.bmp
/overviews/de_aisle.txt