//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/de_crisis.html
halflife.wad
sound/ambience/crow.wav
cstrike.wad
gfx/env/greenbk.tga
gfx/env/greendn.tga
gfx/env/greenft.tga
gfx/env/greenlf.tga
gfx/env/greenrt.tga
gfx/env/greenup.tga
sound/ambience/birds4.wav
sound/ambience/waterrun.wav
decals.wad
sound/ambience/dog1.wav
sound/ambience/g_priester.wav
sound/de_prodigy2k/wind.wav
crisis.wad
maps/de_crisis.bsp
maps/de_crisis.txt
