//////////////////////////////////////////////////////////
// Resources file, created with 17buddies php script!!! //
// © Chapo 2005-2007 - Infos @ http://www.17buddies.net //
//          More than 15000 maps to download!           //
//                                                      //
//      Can you play all of our maps ?? Sure not!!      //
//////////////////////////////////////////////////////////
//
// Res file generated by mikado for 17Buddies.
//
// Map Name  : de_dustyaztec
//
// Download @: http://dwl.17buddies.net/link/map/12056/de_dustyaztec.html
//
//////////////////////////////////////////////////////////
 
gfx/env/Spaceup.tga
gfx/env/Spacedn.tga
gfx/env/Spacelf.tga
gfx/env/Spacert.tga
gfx/env/Spaceft.tga
gfx/env/Spacebk.tga
