sound/ambience/extreme1.wav
gfx/env/ashUp.tga
gfx/env/ashDn.tga
gfx/env/ashLf.tga
gfx/env/ashRt.tga
gfx/env/ashBk.tga
gfx/env/ashFt.tga
maps/de_kalt.txt
maps/de_kalt.bsp
maps/de_kalt.res
maps/overviews/de_kalt.txt
maps/overviews/de_kalt.bmp