//////////////////////////////////////////////////////////
// Resources file, created with 17buddies php script!!! //
// © Chapo 2005-2007 - Infos @ http://www.17buddies.net //
//          More than 15000 maps to download!           //
//                                                      //
//      Can you play all of our maps ?? Sure not!!      //
//////////////////////////////////////////////////////////
//
// Res file generated by mikado for 17Buddies.
//
// Map Name  : de_museum
//
// Download @: http://dwl.17buddies.net/link/map/299/de_museum.html
//
//////////////////////////////////////////////////////////
gfx/env/museum_up.tga
gfx/env/museum_dn.tga
gfx/env/museum_lf.tga
gfx/env/museum_rt.tga
gfx/env/museum_ft.tga
gfx/env/museum_bk.tga

sound/ambience/mtrex.wav
sound/ambience/fallscream.wav
sound/ambience/mcity.wav
sound/ambience/mbigfan.wav
sound/ambience/mvoice.wav
