//////////////////////////////////////////////////////////
// Resources file, created with 17buddies php script!!! //
// © Chapo 2005-2013 - Infos @ http://www.17buddies.net //
//          More than 85000 maps to download!           //
//////////////////////////////////////////////////////////
// Map Name  : de_romania
// Download @: http://www.17buddies.net/17b2/View/Map/56015/de_romania.html
// (.res file generated by djsukaru with script version 3.0)
//////////////////////////////////////////////////////////
// Wad files legend:
//     *  : Hardcoded in bsp file, this wad was found (in
//          archive or on 17Buddies's website) but doesn't
//          contains any used texture.
//          However, this file may be necessary.
//     ** : Hardcoded in bsp file, this wad could not be
//          found (neither in archive nor on 17Buddies's
//          website) and thus could not be analysed.
//          However, this file may be necessary.
//////////////////////////////////////////////////////////
as_rising_sun.wad
// models/player/guerilla/guerilla.mdl
// models/player/gsg9/gsg9.mdl
